# Personal info
name: Kunlin Han
email: kunlinha@usc.edu
# phone: 123-456-7890
website: https://www.linkedin.com/in/kunlinhan/
extra_links:
  - Github (Karl-Han): https://github.com/Karl-Han
  - Personal Website: https://www.iwktd.com/

order:
  - Education
  - Skills
  - Experience
  - Projects
  - Leadership and Involvement

content:
  - title: Summary
    layout: text
    content: 
      - Proactive learner who changed Master degree from Computer Science to Electrical Engineering at USC (GPA 4.0).
      - Self-motivated and problem-solving student working on UVM-based testbench for functional digital verification and OpenSPARC T1 for computer architecture design. 
      - Participated proactively in courses and organized study groups. Passionate about building bonds with local community. 
      - Eager to join $<company>$ as $<title>$ to contribute to $<company's benefit>$.
  - title: Education
    layout: list
    content:
      - title: University of Southern California (USC)
        location: Los Angeles, CA
        sub_title: |
          Master of Electrical Engineering; GPA: 4.0/4.0
        duration: 12/2021-12/2023
      - title: South China Normal University (SCNU)
        location: Guangzhou, China
        sub_title: |
          Bachelor of Network Engineering; GPA: 3.78/4.0; Rank: 1/72
        duration: 09/2017-06/2021

  - title: Experience
    layout: list
    content:
      - title: CS Department, USC
        location: Los Angeles, CA
        sub_title: Graduate Teaching Assistant
        duration: 05/2022-08/2022
        link: https://bytes.usc.edu/cs455saty/m22_Coding-Rocks/home/index.html
        # description: 
        #   - Coordinated with Prof. Saty Raghavachary as teaching assistant (course producer) in CSCI-455X Introduction to Programming Systems Design.
        #   - Presented labs to help students to understand the usage and importance of debugging (GDB) and get an overview of Computer Systems.
        #   - Held weekly office hours to help students with problems in assignments and labs.
      - show: false
        title: Lab 131, School of Computer Science, SCNU
        location: Los Angeles, CA
        sub_title: Instructor
        duration: 09/2018-06/2021
        # description: 
        #   - Recruited and manage members for the Lab. 
        #   - "Organized and instructed members to study CS topics: Algorithm (CLRS), Linear Algebra (GSLA), Computer System (CSAPP), Computation Theory (ITOC) and Functional Programming (SICP). "

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - title: Tomasulo Out-of-order CPU
        location: 06/2023-08/2023
        description: 
          - Implemented Issue Unit, 2-stage Dispatch Unit, Re-Order Buffer and FPGA-friendly Copy-Free Check Pointing, which restores FRAT with RRAT.
          - Integrated, synthesized and programmed the overall system on Xilinx Artix-7 FPGA board.
          - Validated the correctness of design with both simulation and on-ship logic analyzer (Chipscope).
      - title: 512-bit 6T SRAM Array Design
        location: 01/2023-05/2023
        description: 
          - Designed and drew layout of 1-bit SRAM cell, row/column decoders, sense amplifier, write driver, precharge circuit, latch and flip-flop with Cadence Virtuoso and GPDK 45nm.
          - Achieved the Read SNM of 210 mV and Write SNM of 395 mV by proper sizing with VDD=1V while minimizing the size of 1-bit SRAM cell.
          - Integrated components into 4 8x16-bit SRAM banks to construct a 512-bit SRAM Array with the area of 2208 $nm^2$ in 2.6 Ghz (cycle time=0.4 ns).
          - Measured the power consumption with Spectre, in which the average consumption for reading is 21.2 fJ, the average consumption for writing is 342 fJ and leakage is around 20 fJ.
          - Validate the functionality of all aforementioned components with vector in Spectre and clear DRC and LVS errors.
      - title: Extensible Asynchronous SNN Accerlator
        location: 01/2023-05/2023
        description: 
          - Designed extensible asynchronous SSN accelerator in SystemVerilog with SystemVerilogCSP library on a 5x5 filter and 25x25 ifmap with stride=1.
          - Implemented fork-join computation module that can calculate part of the overall computation with pre-configured parameter for extensibility.
          - Integrated computation modules with two memory modules, which contain filter map and ifmap respectively, on a mesh network.
          - Verified correctness of computation module and the accelerator separately with timestep=2 in QuestaSim.
      - show: false
        title: 5-stage Pipeline MIPS Processor
        location: 09/2022-10/2022
        description: 
          - Described Data Path Unit and Control Unit for single-cycle CPU with basic MIPS instructions.
          - Resolved problems related to Data Dependency and Early Branching.
          - Utilized Verilog to build 5-stage pipeline with encoded control signal, Internal Forwarding Register File and Early Branching.
      - title: Full-Custom Design Layout of Arbiter System with Multiplier and Divider
        location: 11/2022-12/2022
        description: 
          - Designed, implemented and drew layout of a ALU supporting 5-bit multiplication and 10-bit division and a 2-1 Round-Robin-based Arbiter with multiply and divide request with the Cadence Virtuoso and GPDK 45nm.
          - Planned, routed and simulated all aforementioned components with Cadence Virtuoso and Spectre and clear DRC and LVS errors with Mentor Graphics Calibre. 

  - title: Leadership and Involvement
    layout: list
    content: 
      - title: Hope Center, Reality L.A.
        location: Los Angeles, CA
        sub_title: Volunteer
        duration: 03/2022-08/2022
        # description: 
        #   - Sorted, organized and shelved food donations for storage to preserve food and accelerate cooking.
        #   - Managed and distributed cooked food with other volunteers.
        #   - Coordinated and collaborated in cleaning utensils after food distribution. 
      - title: Network Club, SCNU
        location: Guangzhou, China
        sub_title: Vice President of Technical Department
        duration: 09/2017-06/2019
        # description: 
        #   - Managed existing members and held interviews to recruit members for Technical department.
        #   - Provided technical supports to on-campus IT activities, including development and maintenance of school forum, holding CTF competition.
        #   - Organized members to write articles about popular computer-related topics, such as resolution of DNS, anti-phishing, and published them in social media to enrich students' knowledge. 

  - title: Skills
    layout: text
    content: 
      - Programming Languages: Python, C/C++, Verilog, VHDL, SystemVerilog, Java, Rust, SQL, x86 ASM
      - Libraries: Scrapy, BeautifulSoup, Requests, Pyrogram, Django
      # - Cadence Tools: Virtuoso, Spectre
      # - Mentor Graphics Tools: ModelSim, QuestaSim, Calibre
      - EDA Tools: Virtuoso, Spectre, QuestaSim, Calibre, Intel Quartus, Xilinx Vivado
      - Protocols: AXI, PCIe, MOESI \hspace{\fill} \textbf{Tools:} UNIX, Linux, VIM, Git, Docker, Makefile
