basics:
  email: true
  extra_links: true
  name: true
  phone: false
  website: true
order:
- mode: none
  section_name: Summary
- mode: all
  section_name: Education
  title:
  - University of Southern California (USC): all
  - South China Normal University (SCNU): all
- mode: enabled
  section_name: Experience
  title:
  - CS Department, USC: no_description
  - Lab 131, School of Computer Science, SCNU: none
- mode: enabled
  section_name: Projects
  title:
  - Branch Predictor and Prefetcher Implementation and Simulation: all
  - Arm Cortex-A7 MPCore Block-Level Implementation: none
  - Performance Analysis of Predictors with Pin Tool: none
  - Tomasulo Out-of-Order CPU Design: all
  - PCIe Physical Layer Design: none
  - General Purpose Graphical Processing Unit (GPGPU): none
  - 512-bit 6T SRAM Array Design: all
  - Extendable Asynchronous SNN Accerlator Design: all
  - 5-stage Pipeline MIPS Processor Design: none
  - Full-Custom Design Layout of Arbiter System with Multiplier and Divider: none
  - RSA, AES and SHA-3 Implementation in Rust: none
- mode: enabled
  section_name: Leadership and Involvement
  title:
  - Hope Center, Reality L.A.: no_description
  - Network Club, SCNU: no_description
- mode: all
  section_name: Skills
